# Generated by Django 6.0.7 on 2026-08-02 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='number_number',
            new_name='plate_number',
        ),
    ]
