# Generated by Django 6.0.7 on 2026-08-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_number_number_car_plate_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='client',
            new_name='owner',
        ),
    ]
