# Generated by Django 6.0.7 on 2026-08-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_plate_number_alter_car_vin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='plate_number',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(default='', max_length=17, unique=True),
            preserve_default=False,
        ),
    ]
