# Generated by Django 6.0.7 on 2026-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('mechanic', 'Mechanic'), ('client', 'Client')], default='client', max_length=20),
        ),
    ]
