# Generated by Django 6.0.7 on 2026-07-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('manager', 'Manager'), ('online', 'Online')], default='dgdf'),
            preserve_default=False,
        ),
    ]
