# Generated by Django 6.0.7 on 2026-08-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'confirmed'), ('in_work', 'In work'), ('ready', 'Ready'), ('complited', 'Complited'), ('canceled', 'Canceled')], default='pending'),
        ),
    ]
